name: Pipeline CI/CD - Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build-and-deploy
    name: iniciando build e deploy
    runs-on: ubuntu-latest
    enviromments: production
    